# -*- coding: utf-8 -*-
"""DAP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L1DZYAgB1q0M5a13KfLQjkdXyTGf9yFY

*   List item
*   List item
"""

import numpy as np
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

for i in range(len(X)):
    for j in range(len(X[0])):
           result[i][j] = X[i][j] + Y[i][j]

for r in result:
   print(r)

import numpy as np
#creating arrays
arr=np.array([1,2,3,4,5])
print(arr)
zeros_arr = np.zeros((3,3), dtype=int)
print(zeros_arr)
arange_arr= np.arange(10)
print(arange_arr)
reshape_arr = arr.reshape(5,1)
print(reshape_arr)
sliced_arr = arr[2:4]
print(sliced_arr)
ones_arr= np.ones((2,2), dtype=int)
print(ones_arr)

import numpy as np
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])
result= arr1+arr2
print(result)
arr=np.array([3,4,5])
a=arr+3
print(a)
c =np.vstack(arr1 + arr2)
print(c)
e= np.array([[1,2,3],[4,5,6]])
f= np.split(e,2)
print(f)
b= e.T
print(b)

m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
d=np.dot(m1,m2)
print(d)
g=np.linalg.eig(d)
print(g)

import numpy as np
m1= np.array([[1,2,3],
 [4,5,6]])
a=np.sum(m1)
print(a)
b=np.sum(m1,axis=0)
print(b)
c=np.sum(m1,axis=1)
print(c)
d=np.array([1,2,3,4,5])
me=np.mean(d)
med=np.median(d)
va=np.var(d)
print(me)
print(med)
print(va)

data = np.loadtxt("/content/data1.txt",dtype=int)
print(data)
data=np.savetxt("/content/data2.txt",data)
print(data)





import matplotlib.pyplot as plt
a= np.array([1,2,3,4,5,6,7,8,9,10])
plt.plot(a)

import pandas as pd
a= ["Madhuri", "Sravani", "Satya", "Iswarya", "Keerthi", "Harshitha"]
r= pd.Series(a,index =[33,45,11,62,54,53])
print(r)
df = pd.read_csv("/content/books_data.csv")
print(df)
df = pd.read_csv("/content/file book.txt",sep="  ")
print(df)

df = pd.read_excel("/content/balance.xlsx")
print(df)
df = pd.read_excel("/content/balance.xlsx",sheet_name=1)
print(df)
df = pd.read_csv("/content/file book.txt",sep="  ")
print(df.loc[1])

df = pd.read_csv("/content/books_data.csv")
mv = df['Sales_in_millions'].mean()
df = df.fillna(mv)
print(mv)
df["class"]=1
df["class"]=0
df = df.drop_duplicates()
print(df)
df.head(8)
df.tail(10)

from google.colab import drive
drive.mount('/content/drive')

df=pd.read_csv("/content/books_data.csv")
a=df.head(8)
b=df.tail(10)
shape=df.shape
print(shape)
df=pd.concat([a,b],axis=0)
df.to_csv("df.csv")
print(df)

df=pd.read_csv("/content/books_data.csv", sep=',')
print(df.groupby(['First_Published'])['Sales_in_millions'].count())

import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.scatter(runs,w,color='orange')
plt.title('INDvsAUS_score')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.plot(runs,w,color='orange')
plt.title('INDvsAUS_score')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
tigar = np.linspace(-2*np.pi,2*np.pi,100)
print(tigar)
plt.plot(tigar, np.sin(tigar) ,color='black')
plt.title("sin(x)")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
overs= np.arange(5,50,5)
overs_a = np.arange(5,30,5)
runs_i= np.array([25,51,84,131,160,189,220,250,267])
runs_a = np.array([15,41,94,110,151])
wicket = np.array([12,32,96])
plt.plot(overs,runs_i,color='blue',label='India')
plt.plot(overs_a,runs_a,color='yellow',label='Aus')
plt.legend(loc='best')
plt.show()

import numpy as np
import matplotlib.pyplot as plt
overs= np.arange(5,50,5)
overs_a = np.arange(5,30,5)
runs_i= np.array([25,51,84,131,160,189,220,250,267])
runs_a = np.array([15,41,94,110,151])
wicket = np.array([12,32,96])
plt.subplot(2,1,2)
plt.plot(overs,runs_i,color='blue',label='India')
plt.legend(loc='best')
plt.subplot(2,1,1)
plt.plot(overs_a,runs_a,color='yellow',label='Aus')
plt.legend(loc='best')
plt.show()

import matplotlib.pyplot as plt
a=[230,560,780,127,128]
b=[200,160,270,127,400]
years = [1,2,3,4]
profit_a=[(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(years,profit_a,color='hotpink',linewidth = '2',label='CompanyA',marker='>',ms='15',mec='k')
plt.legend(loc='best')
plt.subplot(2,1,1)
plt.plot(years,profit_b,color='purple',linestyle = 'dotted',label='CompanyB',marker='H')
plt.legend(loc='best')
plt.show()

a=np.array([25,60,5,10])
labe = ["CSE","PYTHON","Pandas","Numpy"]
plt.pie(a,labels = labe)
plt.legend(loc='best')
plt.show()

a=np.array([25,60,5,10])
labe = ["CSE","PYTHON","Pandas","Numpy"]
explo =[0.2,0,0,0]
plt.pie(a,labels = labe,explode = explo,startangle = 180)
plt.legend(loc='best')
plt.show()

a=np.array([25,60,5,10])
labe = ["CSE","PYTHON","Pandas","Numpy"]
c=["lightgreen","hotpink","blue","orange"]
plt.pie(a,labels = labe,colors=c,textprops={'fontsize':34})
plt.legend(loc='best')
plt.show()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("/content/city_temperature.csv")
print(df)
average_temparature = df['AvgTemperature'].mean()
highest_temparature = df['AvgTemperature'].max()
lowest_temperature = df['AvgTemperature'].min()
threshold=30
days_above_threshold=df[df['AvgTemperature']>threshold].shape[0]
print("Average temperature for the mont:",average_temparature)
print("Highest temparature record:",highest_temparature)
print("Lowest_temperature recorded:",lowest_temperature)
print("Number of days where temperature exceeded",threshold,"degrees celsius:",days_above_threshold)
df.plot(kind='line',color='red')
plt.title('Jan month temp')
plt.xlabel('days')
plt.ylabel('temp')
plt.show()

pip install seaborn

import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
sns.scatterplot(x="total_bill", y="tip", data=tips)
plt.title("Scatter plot of Total Bill vs.Tip")
plt.xlabel("Total Bill ($)")
plt.ylabel("Tip ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt

# Load the anscombe dataset
anscombe = sns.load_dataset("anscombe")

# Display the first few rows of the dataset to understand its structure
print(anscombe.head())

# Plot the four datasets in the anscombe dataset
sns.set(style="ticks")
sns.lmplot(x="x", y="y", col="dataset", hue="dataset", data=anscombe,
           col_wrap=2, ci=None, palette="muted", height=4,
           scatter_kws={"s": 50, "alpha":1})
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
sns.violinplot(x="day",y="total_bill",data=tips)
plt.title("Distribution of Total Bill by Day")
plt.xlabel("Day of the Week")
plt.ylabel("Total Bill ($)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset("iris")
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("correlation Heatmap of Iris Dataset")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
iris = sns.load_dataset("titanic")
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm")
plt.title("correlation Heatmap of Iris Dataset")
plt.show()